<?php
  
  $movies = [
    new Movie("Titanic", "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.", new Director("James", "Cameron"), 1997, [new Genre("Drama"), new Genre("Romance")], 194, 7.9, "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg"),
    new Movie("Avatar", "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.", new Director("James", "Cameron"), 2009, [new Genre("Action"), new Genre("Adventure"), new Genre("Fantasy"), new Genre("Science Fiction")], 162, 7.6, "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg"),
    new Movie("Yuku and the Himalayan Flower", "Yuku is a young mouse who lives with her family in the cellar of a castle. Her grandmother passes on the family values by telling her timeless folk tales. Injured in a tussle with a cat, the old mouse is bedridden and she tells her children that she will have to leave them to follow the little blind mole into the Earth’s tunnels. In one of her grandmother’s storybooks, Yuku learns that the flower of the Himalayas can bring her eternal light. She leaves on a journey of discovery to find the flower.", new Director("Rémi", "Durin"), 2022, [new Genre("Animation"), new Genre("Family"), new Genre("Adventure")], 65, 1.7, "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8bBmqaVxQFtdLJYB0CCcuwnhptc.jpg"),
    new Movie("The Imitation Game", "Based on the real life story of legendary cryptanalyst Alan Turing, the film portrays the nail-biting race against time by Turing and his brilliant team of code-breakers at Britain's top-secret Government Code and Cypher School at Bletchley Park, during the darkest days of World War II.", new Director("Morten", "Tyldum"), 2014, [new Genre("History"), new Genre("Drama"), new Genre("Thriller"), new Genre("War")], 113, 8, "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg"),
    new Movie("Inception", "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.", new Director("Christopher", "Nolan"), 2010, [new Genre("Action"), new Genre("Science Fiction"), new Genre("Adventure")], 148, 8.4, "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg"),
    new Movie("Guardians of the Galaxy Vol. 3", "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.", new Director("James", "Gunn"), 2023, [new Genre("Science Fiction"), new Genre("Adventure"), new Genre("Action")], 150, 8.2, "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg"),
    new Movie("Winnie the Pooh: Blood and Honey", "Christopher Robin is headed off to college and he has abandoned his old friends, Pooh and Piglet, which then leads to the duo embracing their inner monsters.", new Director("Rhys", "Frake-Waterfield"), 2023, [new Genre("Horror"), new Genre("Thriller")], 84, 5.7, "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ewF3IlGscc7FjgGEPcQvZsAsgAW.jpg"),
    new Movie("Guillermo del Toro's Pinocchio", "During the rise of fascism in Mussolini's Italy, a wooden boy brought magically to life struggles to live up to his father's expectations.", new Director("Guillermo", "del Toro"), 2022, [new Genre("Animation"), new Genre("Fantasy"), new Genre("Drama"), new Genre("Music")], 117, 8.2, "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vx1u0uwxdlhV2MUzj4VlcMB0N6m.jpg"),
    new Movie("The Whale", "A reclusive English teacher suffering from severe obesity attempts to reconnect with his estranged teenage daughter for one last chance at redemption.", new Director("Darren", "Aronofsky"), 2022, [new Genre("Drama")], 116, 8, "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/jQ0gylJMxWSL490sy0RrPj1Lj7e.jpg"),
    new Movie("The Green Mile", "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.", new Director("Frank", "Darabont"), 1999, [new Genre("Fantasy"), new Genre("Drama"), new Genre("Crime")], 189, 8.5, "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg"),
    new Movie("The Dark Knight", "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.", new Director("Christopher", "Nolan"), 2008, [new Genre("Drama"), new Genre("Action"), new Genre("Crime"), new Genre("Thriller")], 152, 8.5, "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qJ2tW6WMUDux911r6m7haRef0WH.jpg"),
    new Movie("Howl's Moving Castle", "When Sophie, a shy young woman, is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.", new Director("Hayao", "Miyazaki"), 2004, [new Genre("Fantasy"), new Genre("Animation"), new Genre("Adventure")], 119, 8.4, "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yeJ5Nj1k2NA0bBZjkZ10PvQKjTD.jpg")
  ];
